# Nacos Service 配置
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: springcloud-alibaba
  labels:
    app: nacos
spec:
  ports:
    - port: 8848
      name: client-port
      targetPort: 8848
    - port: 9848
      name: client-grpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
  clusterIP: None
  selector:
    app: nacos
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: springcloud-alibaba
  labels:
    app: nacos
spec:
  type: ClusterIP
  ports:
    - port: 8848
      name: client-port
      targetPort: 8848
      protocol: TCP
    - port: 9848
      name: client-grpc
      targetPort: 9848
      protocol: TCP
    - port: 9849
      name: raft-rpc
      targetPort: 9849
      protocol: TCP
  selector:
    app: nacos
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-ui
  namespace: springcloud-alibaba
  labels:
    app: nacos
    component: ui
spec:
  type: LoadBalancer
  ports:
    - port: 8848
      targetPort: 8848
      name: http
      protocol: TCP
  selector:
    app: nacos
