apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: springcloud-alibaba
type: Opaque
stringData:
  root-password: "Root@123456"
  username: "app"
  password: "App@2024"
  replication-password: "Repl@2024"
  # Nacos
  nacos-username: "nacos"
  nacos-password: "nacos@2024"
  # Seata
  seata-username: "seata"
  seata-password: "seata@2024"
