apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: flash-sale
  labels:
    app: order-service
spec:
  ports:
  - port: 8082
    name: http
    targetPort: 8082
  - port: 8083
    name: management
    targetPort: 8083
  selector:
    app: order-service
  type: ClusterIP
  sessionAffinity: None
