apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: ecommerce
  labels:
    app: nacos
spec:
  ports:
  - port: 8848
    name: client-port
  - port: 9848
    name: client-rpc
  - port: 9849
    name: raft-rpc
  clusterIP: None
  selector:
    app: nacos

---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: ecommerce
  labels:
    app: nacos
spec:
  type: ClusterIP
  ports:
  - port: 8848
    targetPort: 8848
    name: client-port
  - port: 9848
    targetPort: 9848
    name: client-rpc
  - port: 9849
    targetPort: 9849
    name: raft-rpc
  selector:
    app: nacos

---
apiVersion: v1
kind: Service
metadata:
  name: nacos-public
  namespace: ecommerce
  labels:
    app: nacos
spec:
  type: LoadBalancer
  ports:
  - port: 8848
    targetPort: 8848
    name: client-port
  selector:
    app: nacos
